### ISSUE TITLE
Failed to activate the coffeescript-check package

### ISSUE THREAD

**Issue by fincha** [leny/atom-coffeescript-check#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [coffeescript-check](https://github.com/leny/atom-coffeescript-check) package, v0.0.3

### Stack Trace

Failed to activate the coffeescript-check package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/fribu/.atom/packages/coffeescript-check/lib/coffeescript-check.coffee:31:27)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:419:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:414:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:636:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:91:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:32:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
coffeescript-check, v0.0.3
coffeescript-preview, v1.0.0
color-picker, v1.7.0
html-entities, v0.3.1
html-tab, v1.0.1
jshint, v1.3.5
language-lua, v0.9.2
linter, v0.12.1
linter-lua, v0.1.5
linter-luacheck, v0.3.3
text-to-string-for-javascript-converter, v0.0.7

# Dev
No dev packages
```

**Comment by leny** [comment]
Fixed in version `0.1.0`. Thanks for the report.
